### PR TITLE
Use feature for tracking_id

### PR DESCRIPTION
**Pull request by lxfind**
As we discussed, allow the upstream client to choose to whether use this feature.
Also, the current implementation of tracking_id in sui no longer requires customized deserialization. Revert the trait requirement.

### CODE REVIEW

**Review by huitseeker — APPROVED** [review]
Thanks lxfind! The breaking change is probably on the Sui side, with a custom feature activation, I guess.

**Comment by lxfind** [comment]
The removal of the trait function (not the feature) is what would make this a breaking change.

**Comment by andll** [comment]
This is not really a breaking change right? Aside from need to update sui code it does not break validator compatibility. E.g. "breaking change" is a marker for PE that they need to take extra steps during deployment, but this does not happen here

**Comment by lxfind** [comment]
Ahh I completely misunderstood the meaning of "breaking-change" (I thought it means something that would cause Sui to fail to build)

**Pull request merged**
