### PR TITLE
Clients support

### PR DESCRIPTION
**Pull request by asonnino**
This PR is part of our story to allow Tusk/Bullshark to support light clients.

### What this PR does:
* Implementation of persistent storage for the consensus. Consensus should now be able to crash-recover safely, but there is still an issue to fix to make it live (https://github.com/MystenLabs/sui/issues/5200). We should support crash-recover for both the consensus node and the light clients.
* Add a subscriber module accepting connections from clients and serving them the consensus output sequence.
* Implement a synchroniser helping slow/crash-recovered clients to get up to speed.

### In a next PR:
* Limit the number of subscribers a node can handle (DoS resistance): https://github.com/MystenLabs/narwhal/issues/109
* Rather than dropping connections with clients when things go wrong, engage in a helpful dialogue: https://github.com/MystenLabs/narwhal/issues/107
* Finish the last bit to make consensus' crash-recovery live: https://github.com/MystenLabs/sui/issues/5200
* Make a facility to serve block contents to subscribers (not only certificates)

### CODE REVIEW

**Review by akichidis — COMMENTED** [review]
Changes look good to me! Left a few comments. Could you also please include a test file for the component?

**Review by huitseeker — DISMISSED** [review]
The Main concern: once the consensus module on the primary is suitably amended to have fault tolerance, it should be the source of Truth for consensus metadata (which blocks and rounds have been committed) as well as actual block storage.

How do you plan to address the separation of concerns with the subscriber?

At the moment, it seems this duplicates functionality intended for the consensus, and will seek to increase the duplication, at a prohibitive cost in performance (https://github.com/MystenLabs/narwhal/pull/11#issuecomment-982237263).

**Review by huitseeker — COMMENTED** [review]
1. This breaks consensus micro-benchmarks in the consensus module:
https://gist.github.com/4c942c60322c89117ddd9d3eb53ba308
2. The moment this is fixed, it should give us a precise answer to #116

**Review by huitseeker — COMMENTED** [review]
Overall this LGTM but I've noted a number of issues important to mop up in the code.

As far as perf is concerned:

## Before

```sh
processing certificates/batched/400
                        time:   [187.90 us 188.59 us 189.38 us]
                        thrpt:  [620.42 MiB/s 623.01 MiB/s 625.29 MiB/s]
Found 9 outliers among 100 measurements (9.00%)
  7 (7.00%) high mild
  2 (2.00%) high severe
processing certificates/batched/2000
                        time:   [932.19 us 934.38 us 936.62 us]
                        thrpt:  [627.22 MiB/s 628.72 MiB/s 630.19 MiB/s]
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) low severe
  3 (3.00%) low mild
  2 (2.00%) high mild
  2 (2.00%) high severe
processing certificates/batched/4000
                        time:   [1.9348 ms 1.9479 ms 1.9640 ms]
                        thrpt:  [598.23 MiB/s 603.19 MiB/s 607.27 MiB/s]
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe
processing certificates/batched/20000
                        time:   [10.446 ms 10.559 ms 10.677 ms]
                        thrpt:  [550.22 MiB/s 556.35 MiB/s 562.40 MiB/s]
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

## After

```sh
processing certificates/batched/400
                        time:   [186.86 us 187.23 us 187.59 us]
                        thrpt:  [626.31 MiB/s 627.54 MiB/s 628.78 MiB/s]
                 change:
                        time:   [-0.0376% +0.2838% +0.5571%] (p = 0.06 > 0.05)
                        thrpt:  [-0.5540% -0.2830% +0.0376%]
                        No change in performance detected.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
processing certificates/batched/2000
                        time:   [939.89 us 941.90 us 943.94 us]
                        thrpt:  [622.35 MiB/s 623.70 MiB/s 625.03 MiB/s]
                 change:
                        time:   [+0.5497% +0.8208% +1.0750%] (p = 0.00 < 0.05)
                        thrpt:  [-1.0635% -0.8141% -0.5467%]
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
processing certificates/batched/4000
                        time:   [1.9007 ms 1.9067 ms 1.9129 ms]
                        thrpt:  [614.22 MiB/s 616.21 MiB/s 618.15 MiB/s]
                 change:
                        time:   [-0.2378% +0.3179% +0.8241%] (p = 0.25 > 0.05)
                        thrpt:  [-0.8174% -0.3169% +0.2384%]
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
processing certificates/batched/20000
                        time:   [10.639 ms 10.722 ms 10.807 ms]
                        thrpt:  [543.60 MiB/s 547.89 MiB/s 552.18 MiB/s]
                 change:
                        time:   [+3.5901% +4.8038% +5.8999%] (p = 0.00 < 0.05)
                        thrpt:  [-5.5712% -4.5836% -3.4656%]
                        Performance has regressed.
```

As far as I'm concerned that's ok perf-wise.

**Review by huitseeker — APPROVED** [review]
Super! the perf is stable-ish, this looks good to go!

**Review by akichidis — COMMENTED** [review]
Great work! 👍  Some minor comments.

**Pull request merged**
