### PR TITLE
Committee type safety

### PR DESCRIPTION
**Pull request by punwai**
This makes Committee structs type-safe by ensuring that the list of underlying validators in an epoch is immutable. This is required for the following PRs that we will then later push:
1. Replace Public Keys in certificate with Bitmaps.
2. Replace with vector of signatures with Aggregated Signatures

### CODE REVIEW

**Review by huitseeker — CHANGES_REQUESTED** [review]
The `BTreeMap` is already ordered:
https://doc.rust-lang.org/std/collections/struct.BTreeMap.html
> Iterators obtained from functions such as [BTreeMap::iter](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.iter), [BTreeMap::values](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.values), or [BTreeMap::keys](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.keys) produce their items in order by key, and take worst-case logarithmic and amortized constant time per item returned.

This is unecessary.

**Comment by punwai** [comment]
@huitseeker Do we still want this PR for committee's type safety?

**Comment by huitseeker** [comment]
@punwai if by this you mean making authorities a read-only field (i.e. private with a public getter), yes! But it's a small subset of this PR in the current state.

**Comment by punwai** [comment]
Closing for now

**Pull request closed without merging**
