### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by asonnino**

### CODE REVIEW

**Review by velvia — COMMENTED** [review]
+1 thanks @asonnino ...
Maybe every say 100 or 1000 messages you can output an INFO that periodically reminds us it is alive?  :)

**Review by huitseeker — APPROVED** [review]
Definitely a two-way door.

**Comment by lxfind** [comment]
May I ask why do we want to see this even in debug logs? It's like 50 entries per second, would it ever be useful with such high frequency?
Sometimes we print debug info in Sui to help debug stuff, and I suspect this will get in our way (at least for devnet).

**Comment by asonnino** [comment]
yes we can remove some of the logs. It brings 50 entires per second because of the default parameters we use in Narwhal/Sui, otherwise it is arbitrarily slow.

**Pull request merged**
