### PR TITLE
feat: adding the benchmark_client to the images for load testing

### PR DESCRIPTION
**Pull request by allan-bailey**
This will make it simpler to load test the k8s deployments.

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
1. OK, you're getting this binary because you're getting the `--all-features` build

2. Shoot, I realize https://github.com/MystenLabs/narwhal/pull/448 introduced the `dhat-heap` compiler feature, which needs not to be turned on for this Docker image, so it would be great if you could change all instances of `--all-features` into `--features "celo, benchmark"`

**Review by huitseeker — APPROVED** [review]
Thank you so much!

**Review by akichidis — APPROVED** [review]

**Comment by huitseeker** [comment]
@allan-bailey you may need to rebase this one to pass checks: we changed a linter in #485

**Comment by allan-bailey** [comment]
i messed up my rebase. starting over.

**Pull request closed without merging**
