### PR TITLE
Log the start of primary components

### PR DESCRIPTION
**Pull request by mwtian**
Sample log lines:
```
2022-08-03T04:24:07.192145Z DEBUG primary::primary: PrimaryReceiverHandler is starting.
2022-08-03T04:24:07.193491Z DEBUG primary::primary: WorkerReceiverHandler is starting.
2022-08-03T04:24:07.193744Z DEBUG primary::core: Core on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.193840Z DEBUG primary::payload_receiver: PayloadReceiver is starting.
2022-08-03T04:24:07.193894Z DEBUG primary::block_waiter: BlockWaiter on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.193979Z DEBUG primary::block_remover: BlockRemover on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.194043Z DEBUG primary::block_synchronizer: BlockSynchronizer on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.194075Z DEBUG primary::header_waiter: HeaderWaiter on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.194194Z DEBUG primary::certificate_waiter: CertificateWaiter is starting.
2022-08-03T04:24:07.194227Z DEBUG primary::proposer: Dag starting at round 0
2022-08-03T04:24:07.194235Z DEBUG primary::proposer: Proposer on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.194261Z DEBUG primary::helper: Helper for availability requests on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
2022-08-03T04:24:07.194284Z DEBUG primary::state_handler: StateHandler on IP26ybELdYe7p7W8FjvOaeeW1x5O1EwQ/LRIhon3oUQ= is starting.
```

Adding logging to shutdown will be in another change.

### CODE REVIEW

**Comment by mwtian** [comment]
Not sure how code coverage calculation works. IIUC the new log lines should be exercised by bringing up the primary e.g. in `test_new_epoch`.

**Review by huitseeker — COMMENTED** [review]
Thanks a lot for thePR @mwtian ! The only comment i have is that at this stage, what's more useful to us is to capture the end of the startup, in order to assert successful startups.

I think a simple log is fine for now, and given those components do not perform their initial start several times, I think it's fine to log at the INFO level.

If you want to be fancy and really log at the end of the component start (and possibly diagnose failures), it might just be interesting to look at [scopeguard](https://github.com/bluss/scopeguard) - but on this one, done is better than perfect.

**Comment by mwtian** [comment]
As discussed off thread, changed the log level to info and phrasing to "... has started successfully.". These particular componenets do not have initialization errors, but I will use the scoped guard pattern if needs arise in future.

**Review by huitseeker — APPROVED** [review]
Excellent! Thanks @mwtian !

**Pull request merged**
