### PR TITLE
fix: turn off logging stderr+out to file

### PR DESCRIPTION
**Pull request by allan-bailey**
Removing the log file so we can just log to the container
stdout and stderr to be picked up by Loki or other means.

### CODE REVIEW

**Review by huitseeker — COMMENTED** [review]
Do we have an issue to bring in shipping the logs to loki, through e.g. the [tracing subscriber](https://github.com/hrxi/tracing-loki)? Do we moreover have some documentation on how to retrieve those logs through those alternate means (loki or otherwise)?

I'm worried about this suppressing functionality without an alternative in place.

**Comment by allan-bailey** [comment]
> 

I'll create a tracking issue for making logs easily accessible via Loki, or if you're running in docker-compose, the logs would be visible via `docker compose logs`

issue: #455

**Comment by akichidis** [comment]
@allan-bailey I've left a comment on the ticket as well, but to make sure it's not missed, let's make sure that [README](https://github.com/MystenLabs/narwhal/blob/6e86be42032de550764368c4a8a66e1472c68445/Docker/README.md?plain=1#L47) is updated and tell the user where they should expect to find the logs.

**Review by huitseeker — COMMENTED** [review]
> I'll create a tracking issue for making logs easily accessible via Loki, or if you're running in docker-compose, the logs would be visible via docker compose logs

Sounds fair to me. Could you open the Loki issue and update the section on logs in the [Docker README](https://github.com/MystenLabs/narwhal/blob/main/Docker/README.md#quick-start) with a sentence on e.g. `docker compose logs`, that should round up the present PR in a shippable milestone state, I think.

**Comment by allan-bailey** [comment]
Once this new Dockerfile + entry.sh script is on main, I'll be able to fix our workflow to build and push the container image to docker hub.

**Review by huitseeker — APPROVED** [review]
Superb, thanks @allan-bailey !

**Comment by allan-bailey** [comment]
Fixes #455

**Pull request merged**
