### PR TITLE
[refactor] Create the types crate

### PR DESCRIPTION
**Pull request by huitseeker**
The types crate contains all the usual suspects: `Batch`,`Round`, `Header`, `Vote`, `Certificate`, and their digests.

### CODE REVIEW

**Comment by bmwill** [comment]
This is great, I even noticed a lot of duplicate code wrt tests earlier today that we could try to unify at some point.

One thought: Is there much benefit to having all these things broken out into different crates (aside from some compile time benefits)? Would it maybe be easier to reason about if everything was in a single super crate?

**Comment by huitseeker** [comment]
> I even noticed a lot of duplicate code wrt tests earlier today that we could try to unify at some point.

Y u no open issues? 😢 

> Is there much benefit to having all these things broken out into different crates (aside from some compile time benefits)?

Well, outside of philoophy:
- @arun-koshy is blocked on some nominal typing issue (he's trying to write a test for the primary crate and feed to a structure using the primary crate through a re-export). this is one of the ways to make this disappear.
- there's also duplication in the error types that @asonnino that could disappear because of this.

**Review by asonnino — APPROVED** [review]
Why not making `test_utils` a separate crate that we can import under [dev-dependencies] rather than as a standard dependency? 
Does it only contains 'types'?

**Comment by arun-koshy** [comment]
Thanks for doing this @huitseeker!

**Review by arun-koshy — APPROVED** [review]

**Comment by huitseeker** [comment]
> Why not making test_utils a separate crate that we can import under [dev-dependencies] rather than as a standard dependency?

I would see a PR doing that favorably. 
Right now test-utils is a module that's only importable under a non-default feature. It's imported in primary.

**Pull request merged**
